"""add_image_hashes_to_plant_scans

Revision ID: 56b0ea76de45
Revises: b7bbe9ceb80f
Create Date: 2025-12-26 02:00:32.626172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b0ea76de45'
down_revision: Union[str, Sequence[str], None] = 'b7bbe9ceb80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if columns already exist (for existing databases)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Get existing columns and indexes for plant_scans table
    existing_columns = [col['name'] for col in inspector.get_columns('plant_scans')]
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('plant_scans')]
    
    # Only add columns if they don't exist
    if 'image_hash_phash' not in existing_columns:
        op.add_column('plant_scans', sa.Column('image_hash_phash', sa.String(), nullable=True))
    if 'image_hash_dct' not in existing_columns:
        op.add_column('plant_scans', sa.Column('image_hash_dct', sa.String(), nullable=True))
    if 'image_hash_md5' not in existing_columns:
        op.add_column('plant_scans', sa.Column('image_hash_md5', sa.String(), nullable=True))
    if 'is_duplicate' not in existing_columns:
        op.add_column('plant_scans', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    if 'original_scan_id' not in existing_columns:
        op.add_column('plant_scans', sa.Column('original_scan_id', sa.UUID(), nullable=True))
    
    # Only create indexes if they don't exist
    if 'ix_plant_scans_image_hash_dct' not in existing_indexes:
        op.create_index(op.f('ix_plant_scans_image_hash_dct'), 'plant_scans', ['image_hash_dct'], unique=False)
    if 'ix_plant_scans_image_hash_md5' not in existing_indexes:
        op.create_index(op.f('ix_plant_scans_image_hash_md5'), 'plant_scans', ['image_hash_md5'], unique=False)
    if 'ix_plant_scans_image_hash_phash' not in existing_indexes:
        op.create_index(op.f('ix_plant_scans_image_hash_phash'), 'plant_scans', ['image_hash_phash'], unique=False)
    
    # Check foreign keys before adding
    existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('plant_scans')]
    # Foreign key name might be auto-generated, so check by column instead
    fk_columns = [fk['constrained_columns'] for fk in inspector.get_foreign_keys('plant_scans')]
    has_original_scan_fk = any('original_scan_id' in cols for cols in fk_columns)
    
    if not has_original_scan_fk and 'original_scan_id' in existing_columns:
        op.create_foreign_key(None, 'plant_scans', 'plant_scans', ['original_scan_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_scans', type_='foreignkey')
    op.drop_index(op.f('ix_plant_scans_image_hash_phash'), table_name='plant_scans')
    op.drop_index(op.f('ix_plant_scans_image_hash_md5'), table_name='plant_scans')
    op.drop_index(op.f('ix_plant_scans_image_hash_dct'), table_name='plant_scans')
    op.drop_column('plant_scans', 'original_scan_id')
    op.drop_column('plant_scans', 'is_duplicate')
    op.drop_column('plant_scans', 'image_hash_md5')
    op.drop_column('plant_scans', 'image_hash_dct')
    op.drop_column('plant_scans', 'image_hash_phash')
    # ### end Alembic commands ###
