"""add_image_hashes_to_plant_scans

Revision ID: 56b0ea76de45
Revises: b7bbe9ceb80f
Create Date: 2025-12-26 02:00:32.626172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b0ea76de45'
down_revision: Union[str, Sequence[str], None] = 'b7bbe9ceb80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_scans', sa.Column('image_hash_phash', sa.String(), nullable=True))
    op.add_column('plant_scans', sa.Column('image_hash_dct', sa.String(), nullable=True))
    op.add_column('plant_scans', sa.Column('image_hash_md5', sa.String(), nullable=True))
    op.add_column('plant_scans', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    op.add_column('plant_scans', sa.Column('original_scan_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_plant_scans_image_hash_dct'), 'plant_scans', ['image_hash_dct'], unique=False)
    op.create_index(op.f('ix_plant_scans_image_hash_md5'), 'plant_scans', ['image_hash_md5'], unique=False)
    op.create_index(op.f('ix_plant_scans_image_hash_phash'), 'plant_scans', ['image_hash_phash'], unique=False)
    op.create_foreign_key(None, 'plant_scans', 'plant_scans', ['original_scan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant_scans', type_='foreignkey')
    op.drop_index(op.f('ix_plant_scans_image_hash_phash'), table_name='plant_scans')
    op.drop_index(op.f('ix_plant_scans_image_hash_md5'), table_name='plant_scans')
    op.drop_index(op.f('ix_plant_scans_image_hash_dct'), table_name='plant_scans')
    op.drop_column('plant_scans', 'original_scan_id')
    op.drop_column('plant_scans', 'is_duplicate')
    op.drop_column('plant_scans', 'image_hash_md5')
    op.drop_column('plant_scans', 'image_hash_dct')
    op.drop_column('plant_scans', 'image_hash_phash')
    # ### end Alembic commands ###
