"""add_address_to_orders

Revision ID: b7bbe9ceb80f
Revises: 4d427c7005bd
Create Date: 2025-12-25 12:09:22.007794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bbe9ceb80f'
down_revision: Union[str, Sequence[str], None] = '4d427c7005bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
